# CMake configuration
set( DESTINATION_FOLDER "C:/Users/Berry/Documents/shake_build" )
set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${DESTINATION_FOLDER} )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${DESTINATION_FOLDER} )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${DESTINATION_FOLDER} )
set( CMAKE_EXECUTABLE_OUTPUT_PATH   ${DESTINATION_FOLDER} )